### PR TITLE
Create join tournament, fix get tournament

### LINKED ISSUE #50: Implement join tournament
POST /tournament/{id}/join
Request:
{
    "userId" : ​ 13
}
Response: empty

### PR DESCRIPTION
**Pull request by illfate**
Create join tournament into service interface, in mock db, write test. Fix get tournament with empty users.
Close #50.

### CODE REVIEW

File: pkg/mysql/tournament.go [hunk 1]
```diff
@@ -60,3 +61,62 @@ INNER JOIN participants ON id = tournament_id
...
 }
+
+// JoinTournament adds user with passed userID to tournament with passed tournamentID.
+//If tournament or user isn't found, function returns ErrNotFound.
+func (c *Connector) JoinTournament(ctx context.Context, tournamentID, userID int64) error {
+	tx, err := c.db.BeginTx(ctx, nil)
+	if err != nil {
+		return err
+	}
+	defer tx.Rollback()
```
Comment (golangcibot) [inline pkg/mysql/tournament.go]: Error return value of `tx.Rollback` is not checked (from `errcheck`)
