### PR TITLE
Fix incorrect content type headers in responses

### LINKED ISSUE #24: Incorrect content type headers in responses

### PR DESCRIPTION
**Pull request by illfate**
Close #24

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -106,6 +106,7 @@ func (s *Server) addUser(w http.ResponseWriter, req *http.Request) {
 		fmt.Fprintf(w, "can't encode json: %s\n", err)
 		return
 	}
+	w.Header().Set("Content-Type", "application/json")
```
Comment (sashayakovtseva) [inline main.go]: 👎

File: main.go [hunk 2]
```diff
@@ -205,8 +207,10 @@ SELECT id, name, balance
 		w.WriteHeader(http.StatusInternalServerError)
 		return
 	}
+	w.Header().Set("Content-Type", "application/json")
```
Comment (sashayakovtseva) [inline main.go]: 👍
