### PR TITLE
Fix incorrect marker 

### LINKED ISSUE #41: Incorrect column marker in tournament sql-script

### PR DESCRIPTION
**Pull request by illfate**
Close #41

### CODE REVIEW

File: sql/tournament.sql [hunk 1]
```diff
@@ -2,7 +2,7 @@
      id INT NOT NULL AUTO_INCREMENT,
      name VARCHAR(20) NOT NULL,
      deposit INT(10) UNSIGNED NOT NULL,
-     prize INT(10) UNSIGNED NOT NULL,
+     prize INT(10) UNSIGNED,
```
Comment (sashayakovtseva) [inline sql/tournament.sql]: Why removed?
